all: TDTS07_labreport3.pdf

TDTS07_labreport3.pdf: TDTS07_labreport3.tex
	pdflatex TDTS07_labreport3.tex && \
	pdflatex TDTS07_labreport3.tex && \
	pdflatex TDTS07_labreport3.tex

clean:
	rm -f TDTS07_labreport3.toc TDTS07_labreport3.log TDTS07_labreport3.aux TDTS07_labreport3.pdf
